output "role_arn" {
  description = "This is for the ARN of the created IAM role"
  value = aws_iam_role.create_iam_role.arn
}

output "role_name" {
  description = "This is for the name of the created IAM role"
  value = aws_iam_role.create_iam_role.name
}

# when the output for the instance profile is not EC2, the list generated by the count is empty
# so, i used the try to return null instead of trying to fetch the instance profile name from an empty list which will throw an error

output "instance_profile_name" {
  description = "This si for the name of the instance profile created for EC2 service"
  value = try(aws_iam_instance_profile.create_instance_profile[0].name, null)
}